# Generated by Django 5.0.3 on 2024-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.TextField()),
                ('vedagpt_reply', models.TextField()),
                ('user_file', models.FileField(blank=True, null=True, upload_to='user_files/')),
                ('vedagpt_file', models.FileField(blank=True, null=True, upload_to='vedagpt_files/')),
            ],
        ),
    ]
