# Generated by Django 5.0.3 on 2024-03-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_chats_alter_chathistory_user_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chat',
            new_name='chat_Title',
        ),
    ]
