# Generated by Django 5.0.3 on 2024-03-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rename_chat_chathistory_chat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chat_Title',
            new_name='chat_id',
        ),
    ]
