# Generated by Django 5.0.3 on 2024-03-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_rename_chat_title_chathistory_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='chat_id',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
