# Generated by Django 5.0.3 on 2024-03-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_chat_documents_transaction_delete_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='doc',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
