# Generated by Django 5.0.3 on 2024-03-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modelKEY', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
