# Generated by Django 5.0.4 on 2024-05-08 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="chat",
        ),
        migrations.DeleteModel(
            name="LLM_models",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
