# Generated by Django 5.0.5 on 2024-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_delete_llm_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("modelKEY", models.CharField(max_length=100)),
                ("file_path", models.CharField(max_length=100)),
                ("prompt", models.TextField(default="")),
                ("pdf_prompt", models.TextField(default="")),
                ("summarization_prompt", models.TextField(default="")),
            ],
        ),
    ]
